### ISSUE TITLE
Adding new clash mode and associated maps

### ISSUE THREAD

**Issue by navalex** [TeKrop/overfast-api#192]
Hello,

I was making some changes on my website to allow printing informations about the new features of the game, and I discovered that the API does not yet have integrated the new gamemode.

If it's only a change in the `maps.csv` I can probably make a PR, but I don't know if adding a new gamemode in the CSV will or not break something in the API.

Hope you'll understand,

And many thanks for your work it's amazing !

**Comment by TeKrop** [comment]
Hello,

I also have to update the `gamemodes.csv` file, existing because sometimes Blizzard takes some time to update their landing page with the new gamemode. I'll also add the icon and the preview picture.

For now, some test fixtures will also need to be updated. I'm doing a refactoring on another branch to prevent this and make updates easier without reducing tests relevance and accuracy.

I'm handling it and I'll keep you updated 👍

**Comment by TeKrop** [comment]
Added in last release ✅ Let me know if everything is working fine for you 👍
