### ISSUE TITLE
Couldn't get Blizzard page (HTTP 403 error)

### ISSUE THREAD

**Issue by OskarD** [TeKrop/overfast-api#201]
**Describe the bug**

```
{
"error": "Couldn't get Blizzard page (HTTP 403 error) : <html>\r\n<head><title>403 Forbidden</title></head>\r\n<body>\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n</html>\r\n"
}
```

**To Reproduce**
Try to get any player profile, for example: [https://overfast-api.tekrop.fr/players/Maevis-2125](https://overfast-api.tekrop.fr/players/Maevis-2125)

**Comment by TeKrop** [comment]
Hello,

Thank you for the feedback ! It looks like there was a global issue that lasted a few hours. I believe it occurred because my server generated excessive traffic to overwatch.blizzard.com, which led to a temporary ban 🙈. I've resolved the issue for now by disabling the background cache refresh system to limit traffic.

Since I hadn’t anticipated such high traffic when designing the system, I'll be updating it to make it more resilient before reactivating it 👍.

**Comment by OskarD** [comment]
Thanks @TeKrop , really appreciate it! 🥳 It seems to be working again now.

You can add my app to your community list if you'd like: www.counterwatch.app

**Comment by TeKrop** [comment]
Oh, very nice app, will do 😄
