### ISSUE TITLE
Player Lookup Leading To Not Found

### ISSUE THREAD

**Issue by relia1** [TeKrop/overfast-api#207]
**Describe the bug**
Attempting to lookup myself using my battlenet ID leads to a 404

**To Reproduce**
If applicable, steps to reproduce the behavior:
1. Go to https://overfast-api.tekrop.fr/players/Robert-12124

**Expected behavior**
To be able to see my stats since I can on the blizard page
https://overwatch.blizzard.com/en-us/search/?q=Robert#12124

**Comment by TeKrop** [comment]
Hello @relia1,

Thank you for the bug report. I can see the results for "Robert" on the Blizzard page, but your exact profile isn't displayed. This page is calling another URL to make the search, and this is the one I'm using in the API. 

Here is the URL : https://overwatch.blizzard.com/en-us/search/account-by-name/Robert#12124/
If you search for your exact profile, you won't find it in the data :/ 

That's why the API is saying your profile can't be found. Did you make sure your profile privacy is set to "public" ? 
You should have a "Career Profile Visibility" within the "Social" menu for that. You'll also need to quit the game after changing the option for the changes to be effective on Blizzard pages.

Let me know if it solves your issue 👍

**Comment by relia1** [comment]
Dang I had doubled checked visibility, but I have done it from a battlenet account level. Updating the visibility within overwatch allows me to query myself now. Thank you!
