### ISSUE TITLE
[Docker] Several install problems

### ISSUE THREAD

**Issue by navalex** [TeKrop/overfast-api#28]
Hello,

I just installed your api on my VPS, using the docker-compose install. I encountered several issues during the installation, I fixed most of them, but i'm still facing a little one.

1. In the Dockerfile, the apk `build-base` is not found, i replaced it with `g++ make` and it seems to work
2. After, i started up the docker-compose, and it throw me an error in the app_volume, it created a folder instead of a file for the overfast_cron, so i deleted the folder and manually created the file, and it fixed too (at least it launch)
3. And the last issue is that when i call an endpoint, it throw me this in logs:
```
overfast-app-1    | 2023-04-10 12:06:05.423 | INFO     | app.handlers.api_request_handler - Filtering the data using query...
overfast-app-1    | 2023-04-10 12:06:05.435 | WARNING  | app.common.cache_manager - Redis server error : Error 111 connecting to 127.0.0.1:6379. Connection refused.
overfast-app-1    | 2023-04-10 12:06:05.436 | INFO     | app.handlers.api_request_handler - Done ! Returning filtered data...
overfast-app-1    | 2023-04-10 12:06:05.998 | INFO     | logging - 172.18.0.2:34734 - "GET /players/Navalex-21525 HTTP/1.0" 200
```

Even if i put on for redis cache on the env file. I will try to fix it, and keep you in touch, but you can still comment if you know what's going wrong.

**Comment by navalex** [comment]
Maybe it is related to the change on the Dockerfile, does `build-base` install redis-server ?

**Comment by TeKrop** [comment]
Hello :D 

Concerning the warning you have, you can change the `REDIS_HOST` to `redis` instead of `127.0.0.1`, it should solve your warning issue. I'll update the example `.env` accordingly, thank you for the feedback !

Regarding the `build-base` issue, i'll take a look and keep you updated, but it's not related to redis-server, the `Dockerfile` is only for the Python app (uvicorn). Redis is installed using the `redis:alpine` image (see the docker-compose config).

**Comment by navalex** [comment]
Hey back,

I found the problem, for the connection issue with redis. It seems that the `app/config.py` has hard-coded values for
1. `app_base_url: str = "https://overfast-api.tekrop.fr"`
2. `redis_host: str = "127.0.0.1"`
3. `redis_port: int = 6379`
So even if i change the `.env` values it will not reflect in the app. I could make a PR but i'm not really familiar with Python, so i'm not sure if i'll do it right.

**Comment by TeKrop** [comment]
Hmm these values are just here as default values. They should be overriden by the values in the dotenv file because of these lines (https://fastapi.tiangolo.com/advanced/settings/#read-settings-from-env) : 
```
class Config:
    env_file = ".env"
```
Whenever you change a value in the file, you have to restart the app, as the settings are cached in memory (preventing reading the file everytime we make a request).

Concerning the `APP_BASE_URL`, it's only used for the links exposed in some endpoints (players search and maps listing).

**Comment by TeKrop** [comment]
Hello again @navalex,

I made the update on the dotenv and update the README section concerning Docker. You can see the updating version here, don't hesitate to give some feedback in order to know if the process is clear enough now (and working fine) : https://github.com/TeKrop/overfast-api/blob/docker-readme-improvements/README.md

Concerning the `build-base` issue you had, I don't understand why : I made a clean `docker compose build --no-cache` and it worked fine, maybe you had some network issue when you ran the build the first time ? Don't hesitate to tell me if you found out why in the meantime 👍

**Comment by TeKrop** [comment]
@navalex Did you manage to solve the issue on your side ? May I help you on some topic ? 🤔

**Comment by navalex** [comment]
Yeah i made it works by changing the values i show you above manually in the python and dockferile files. Don't know if all my changes were useful but it's working :)
Should i reset my branch to test in an up to date environment ?

**Comment by TeKrop** [comment]
I only updated the README with more detailed steps, so you'll not have any update regarding the process 🤔 If it didn't work for you before, I can't see why it would work now 😅

**Comment by TeKrop** [comment]
@navalex Can I consider this issue as solved, or do you want to try with an up to date environment before ? 🤔

**Comment by TeKrop** [comment]
I consider this issue as solved, don't hesitate to reach me again if you encounter any issue regarding the installation :)
