### ISSUE TITLE
URL of all ranks icons?

### ISSUE THREAD

**Issue by ManHinnn0509** [TeKrop/overfast-api#38]
Sorry for creating an issuse, this is actually a question about the rank icons.
I want to collect all rank icons, wonder if it can be done via the OverFast API.

Use GM3 icon as example, heres the URL of it:
`https://static.playoverwatch.com/img/pages/career/icons/rank/GrandmasterTier-3-e55e61f68f.png`
I noticed that the file name is followed by something like hash code? I mean the `e55e61f68f`, but I wasn't able to figure out how the hashing of it works.

Thank you!

**Comment by TeKrop** [comment]
> Sorry for creating an issuse, this is actually a question about the rank icons.

No problem regarding creating an issue. For future questions, don't hesitate to use the "Discussions" tab (https://github.com/TeKrop/overfast-api/discussions), there is a similar interface to Stack Overflow in order to ask questions and answer 😉 

> I want to collect all rank icons, wonder if it can be done via the OverFast API.

Well, the URL you're referring to is directly retrieved from Blizzard pages (example : https://overwatch.blizzard.com/en-us/career/HarpyForest-2865/). So I'm just taking it as it is, I don't know how the URL is generated on their part 😅 If you want to retrieve all the rank icons, I guess you'll either have to find out how this hash is generated and/or explore all needed profile pages to have all the ranks 🙈

**Comment by ManHinnn0509** [comment]
Thank you for the reply, I'm not familiar with GitHub and I might gonna open a new discussion there.
I have a similar idea in mind, which is go through many player profiles and collect them one by one.
I will share them in a JSON format once I collected them all :D
