### ISSUE TITLE
Blizzard down?

### ISSUE THREAD

**Issue by Backxtar** [TeKrop/overfast-api#40]
```json
{
  "error": "Couldn't get Blizzard page (HTTP 502 error) : <html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n</body>\r\n</html>\r\n"
}
```
Is Blizzard down right now?

**Comment by TeKrop** [comment]
If you encounter this error, there yes this is the error returned by Blizzard when trying to retrieve data from their website. They have downtime sometimes, but it doesn't last long 😉 Is it still happening for you ? 🤔

**Comment by Backxtar** [comment]
i have another issue :)

Missing this gamemode: https://overwatch.fandom.com/wiki/Assault

**Comment by TeKrop** [comment]
Ah 😅 Well it's "normal", the gamemodes exposed in the `/gamemodes` endpoint comes from Overwatch homepage, and "Assault" has been removed on Overwatch 2. I put the concerned maps in the `/maps` endpoint in order to have an history about them, and as they may be used in the future for some new gamemode. 

Is it an issue on your side ? You may just want to not expose them in your app, or create a dedicated section for "old gamemodes" 🤔

**Comment by Backxtar** [comment]
Ah well no, i filter it out i guess
