### ISSUE TITLE
Open queue competitive data somehow filtered out from player stats summary

### ISSUE THREAD

**Issue by ProgressoRU** [TeKrop/overfast-api#44]
I have noticed that sometimes `players/{player_id}/stats/summary` endpoint returns empty response for competitive data despite Blizzard profile page actually shows some competitive stats. So far, I only found 2 such cases and both times the common denominator is players only played in open competitive queue. 

It could be intended behaviour in which case it probably should be added in the docs, but I'm more inclined to think it's a bug as I don't really now how you can reliably remove Open Queue stats. The only two options I could think of is either remove heroes by role, if player doesn't have rank, or to use data-attribute `latestherostatrankseason` (btw: can be useful to add it somewhere into api). I quickly glanced over the code and couldn't find any traces of such filtering. Moreover, `/players/{player_id}` enpoint returns this data just fine.

Profiles in question:
https://overwatch.blizzard.com/en-us/career/Progresso-2749/
https://overfast-api.tekrop.fr/players/Progresso-2749/stats/summary?gamemode=competitive&platform=pc

https://overwatch.blizzard.com/en-us/career/fluffy-24694/
https://overfast-api.tekrop.fr/players/fluffy-24694/stats/summary?gamemode=competitive&platform=pc

(Why Blizzard even mixes up Role Queue with Open queue on their site is a different question but it is what it is, I guess)

**Comment by TeKrop** [comment]
Hello ! Indeed it seems there is a bug in the API, data should be displayed even if it's Open Queue related 🤔 
I'll take a look and keep you updated here 😉

**Comment by TeKrop** [comment]
@ProgressoRU I found the issue in the two cases, it's not related to Open Queue, and I'm worning on a fix : 

- **Progresso-2749** : For the 3 heroes, Blizzard exposes the data "**Games Played : 0**". And we can see that there was 1 game played if we select "All Heroes". If I find this normally not possible value, I guess you played the 3 heroes in the same game, and apparently it doesn't count as 1 full game for Blizzard. Usually, I don't take the statistics as it may be inaccurate. But I'll fix it and will have to consider there was no victory in that case so 0% winrate.
- **fluffy-24694** : The problem is different here, the keys used by Blizzard to expose the data differ depending on the value. If you played 0 game : "Games played : 0". If you played only 1 game, it's singular : "Game played : 0". And then it's plural if you played more than 1 game. I didn't take this behaviour into account and will make a fix.

If you see another profile with a weird behaviour like this, don't hesitate to ping me 😉

**Comment by TeKrop** [comment]
@ProgressoRU I fixed the issue, let me know if everything is OK for you 👍

**Comment by ProgressoRU** [comment]
@TeKrop Everythink is fine now, thanks! Your assumption is totally correct about first case, it was pretty quick stomp.
