### ISSUE TITLE
New URL UID

### ISSUE THREAD

**Issue by MatthewSH** [TeKrop/overfast-api#96]
Noticed this today, Overwatch's website is now redirecting profiles from the name to a UID. For example mine redirects from `Zencep-1489` to `c85ba289b661d6fcbda82e|58a8345296109e00bdcb2af89f4118e3` now. It seems to not impact the API yet? although I can't tell with my profile:
<img width="1050" alt="image" src="https://github.com/TeKrop/overfast-api/assets/3768988/72dc8c17-2447-424c-81ba-910b3d3e6e3b">

I haven't played in season 9 so not sure if it's actually broken yet. Just informing early.

Also complete sidenote, I was wanting to start using Overfast's live instance for collecting player data. I'm not seeing anything about rate limits to the live instance, but is there a rational requests per second you expect without overloading your server?

**Comment by MatthewSH** [comment]
Looking more into it, it looks like search now returns only public profiles.

<details><summary>Screenshots</summary>
<p>

<img width="1489" alt="image" src="https://github.com/TeKrop/overfast-api/assets/3768988/c155d43e-04c8-4ff4-84cd-300f4d3473e5">
<img width="1511" alt="image" src="https://github.com/TeKrop/overfast-api/assets/3768988/e0dec164-7e38-4f5e-8817-a276639cc52d">
<img width="1494" alt="image" src="https://github.com/TeKrop/overfast-api/assets/3768988/61401bf4-e9ae-4ee5-96a2-58a2f314c6c0">

</p>
</details> 

----
It also looks like this new `url` property was added or changed?

<img width="565" alt="image" src="https://github.com/TeKrop/overfast-api/assets/3768988/9cce66c0-f4aa-4ae7-a38f-131293f9d79f">

Still looking into if there's any patterns in the UID to maybe figure out how they're coming up with it.

**Comment by TeKrop** [comment]
> Overwatch's website is now redirecting profiles from the name to a UID. For example mine redirects from Zencep-1489 to c85ba289b661d6fcbda82e|58a8345296109e00bdcb2af89f4118e3 now.

Yes indeed, but the old URLs are redirecting to the new ones, so it's not affecting the API. If someday Blizzard decides to remove the redirection, I'll have some changes to make to make it work again. I don't think it's affecting your profile 👍 

> Also complete sidenote, I was wanting to start using Overfast's live instance for collecting player data. I'm not seeing anything about rate limits to the live instance, but is there a rational requests per second you expect without overloading your server?

Good question, I'll add the information in the README.md and the website. I didn't make any load testing, but I put a reasonable rate limit of 30 requests per second (global limit on the API), so I would advise to not go beyond that (else you'll have an HTTP 429 response from the server).
You may encounter some delay if you're trying to reach several profiles at the same time for the first time on the API, as Blizzard pages take a long time to be loaded. For already reached profiles, it should be smooth thanks to nginx + Redis combination.

> Looking more into it, it looks like search now returns only public profiles.

Yup I can confirm, I also saw it when I made the update last week, and that's why I removed the `privacy` filter option on players search endpoint (and also the `privacy` attribute on players summary). 

> It also looks like this new url property was added or changed?

Yup it's brand new, never seen it before 🤔 

Let me know if I can help you on anything else 👍

**Comment by MatthewSH** [comment]
> Good question, I'll add the information in the README.md and the website. I didn't make any load testing, but I put a reasonable rate limit of 30 requests per second (global limit for any call made on the API), so I would advise to not go beyond that (else you'll have an HTTP 429 response from the server).
Sounds reasonable! thank you!

> You may encounter some delay if you're trying to reach several profiles at the same time for the first time on the API, as Blizzard pages take a long time to be loaded. For already reached profiles, it should be smooth thanks to nginx + Redis combination.
Yeah, I'm guessing there's no way to speed it up either because we're kinda at the whim of their page loads. 😞 If only they provided an API.

> Yup I can confirm, I also saw it when I made the update last week, and that's why I removed the privacy filter option on players search endpoint (and also the privacy attribute on players summary).
Didn't even notice that, I'm finally getting around to implementing it now. Thanks for being so on top of it! <3 

> Yup it's brand new, never seen it before 🤔
Is it possible that property could be added? I'm thinking as a way of prepping for them removing it that I might implement a workflow of taking a username + discriminator and doing a search which should return only one result and storing the generated ID off of that.

I haven't looked on how the API actually works, but I could probably add it if you're busy!

> Let me know if I can help you on anything else 👍
Of course, thank you for working on, IMO, one of the more frequently updated APIs <3 you're a blessing!

**Comment by TeKrop** [comment]
Ah yes definitely! Thank you for the PR, will take a look tomorrow 😉

**Comment by TeKrop** [comment]
@MatthewSH I just merged your PR after some updates, thank you 👍

**Comment by MatthewSH** [comment]
Thank you for the adjustments! I'll keep those in mind for any adjustments in the future!
